version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: career_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  career-portal:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/career_portal
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: