version: '3.8'

services:
  career-portal:
    build:
      context: .
      dockerfile: Dockerfile.replit-env
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://career_user:career_pass@postgres:5432/career_db
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=career_user
      - PGPASSWORD=career_pass
      - PGDATABASE=career_db
      - SESSION_SECRET=your-secret-key-here
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    command: npm run start

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=career_db
      - POSTGRES_USER=career_user
      - POSTGRES_PASSWORD=career_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U career_user -d career_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: