version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: career_portal
      POSTGRES_USER: career_user
      POSTGRES_PASSWORD: career_secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
  app:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://career_user:career_secure_password_2024@postgres:5432/career_portal
    ports:
      - "80:5000"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
volumes:
  postgres_data:
